// <auto-generated />
using System;
using ClubScansub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClubScansub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191021161449_Added image to CourseTemplate")]
    partial class AddedimagetoCourseTemplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClubScansub.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Streetname")
                        .HasMaxLength(150);

                    b.Property<string>("Zipcode")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("ClubScansub.Models.ApplicationUserAccountEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationUserId");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<int?>("EventId");

                    b.Property<DateTime?>("PostingDate");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("EventId");

                    b.ToTable("ApplicationUserAccountEntry");
                });

            modelBuilder.Entity("ClubScansub.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepthLimit");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<int?>("CourseId");

                    b.Property<int?>("CourseSessionTemplateId");

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("DivelocationId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("Sessiontype");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseSessionTemplateId");

                    b.HasIndex("DivelocationId");

                    b.ToTable("CourseSessions");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSessionInstructor", b =>
                {
                    b.Property<int>("CourseSessionId");

                    b.Property<string>("InstructorId");

                    b.Property<bool>("InstructorApproved");

                    b.HasKey("CourseSessionId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessionInstructor");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSessionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseTemplateId");

                    b.Property<TimeSpan>("DefaultDuration");

                    b.Property<TimeSpan>("DefaultStartTime");

                    b.Property<int>("DefaultWeekday");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("SessionNumber");

                    b.Property<int>("SessionType");

                    b.Property<bool>("UseDefaultWeekDay");

                    b.HasKey("Id");

                    b.HasIndex("CourseTemplateId");

                    b.ToTable("CourseSessionTemplate");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSignup", b =>
                {
                    b.Property<string>("ApplicationUserId");

                    b.Property<int>("CourseId");

                    b.HasKey("ApplicationUserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSignup");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcademicSessions");

                    b.Property<int>("CourseType");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("money");

                    b.Property<byte[]>("Image");

                    b.Property<int>("MaxStudents");

                    b.Property<int>("MinStudents");

                    b.Property<int>("OpenWaterSessions");

                    b.Property<int>("PoolSessions");

                    b.Property<string>("TemplateDurationInWeeks");

                    b.Property<string>("TemplateName");

                    b.HasKey("Id");

                    b.ToTable("CourseTemplate");
                });

            modelBuilder.Entity("ClubScansub.Models.Divelocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CertificateId");

                    b.Property<TimeSpan>("DefaultDuration");

                    b.Property<int>("DefaultEventType");

                    b.Property<TimeSpan>("DefaultStartTime");

                    b.Property<string>("Description");

                    b.Property<int>("DiveType");

                    b.Property<byte[]>("Image");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("MaxDepth");

                    b.Property<int?>("MeetingLocationId");

                    b.Property<int>("MinDepth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("MeetingLocationId");

                    b.ToTable("Divelocation");
                });

            modelBuilder.Entity("ClubScansub.Models.DiveorgCertificate", b =>
                {
                    b.Property<int>("DiveorganizationId");

                    b.Property<int>("CertificateId");

                    b.HasKey("DiveorganizationId", "CertificateId");

                    b.HasAlternateKey("CertificateId", "DiveorganizationId");

                    b.ToTable("DiveorgCertificates");
                });

            modelBuilder.Entity("ClubScansub.Models.Diveorganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Diveorganization");
                });

            modelBuilder.Entity("ClubScansub.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("money");

                    b.Property<string>("Details");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("DivelocationId");

                    b.Property<DateTime>("EndDateAndTime");

                    b.Property<int>("EventType");

                    b.Property<int>("FixedParticipants");

                    b.Property<bool>("IsCancelled");

                    b.Property<int>("MaxParticipants");

                    b.Property<int>("MinParticipants");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("RequiredCertificateId");

                    b.Property<DateTime>("StartDateAndTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DivelocationId");

                    b.HasIndex("RequiredCertificateId");

                    b.ToTable("Event");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Event");
                });

            modelBuilder.Entity("ClubScansub.Models.EventUser", b =>
                {
                    b.Property<string>("ApplicationUserId");

                    b.Property<int>("EventId");

                    b.HasKey("ApplicationUserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("ClubScansub.Models.UserCertificat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("BackSideImage");

                    b.Property<int?>("CertificateId");

                    b.Property<byte[]>("FrontSideImage");

                    b.Property<bool>("IsVerified");

                    b.Property<DateTime>("IssuedDate");

                    b.Property<string>("UserId");

                    b.Property<string>("VerifiedById");

                    b.Property<DateTime>("VerifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("UserCertificate");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ClubScansub.Models.Course", b =>
                {
                    b.HasBaseType("ClubScansub.Models.Event");

                    b.Property<string>("CourseName");

                    b.Property<int?>("CourseTemplateId");

                    b.Property<int>("CourseType");

                    b.HasIndex("CourseTemplateId");

                    b.ToTable("Event");

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("ClubScansub.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("AccountNumber");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("DayOfbirth");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Streetaddress");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("ClubScansub.Models.ApplicationUserAccountEntry", b =>
                {
                    b.HasOne("ClubScansub.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("AccountTransactions")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("ClubScansub.Models.Event", "Event")
                        .WithMany("AccountTransactions")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSession", b =>
                {
                    b.HasOne("ClubScansub.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("ClubScansub.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.CourseSessionTemplate", "CourseSessionTemplate")
                        .WithMany()
                        .HasForeignKey("CourseSessionTemplateId");

                    b.HasOne("ClubScansub.Models.Divelocation", "Divelocation")
                        .WithMany()
                        .HasForeignKey("DivelocationId");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSessionInstructor", b =>
                {
                    b.HasOne("ClubScansub.Models.CourseSession", "CourseSession")
                        .WithMany("SessionInstructors")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.ApplicationUser", "Instructor")
                        .WithMany("InstructorSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSessionTemplate", b =>
                {
                    b.HasOne("ClubScansub.Models.CourseTemplate", "CourseTemplate")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseTemplateId");
                });

            modelBuilder.Entity("ClubScansub.Models.CourseSignup", b =>
                {
                    b.HasOne("ClubScansub.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Courses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.Course", "Course")
                        .WithMany("Signups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClubScansub.Models.Divelocation", b =>
                {
                    b.HasOne("ClubScansub.Models.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("ClubScansub.Models.Address", "MeetingLocation")
                        .WithMany("Divelocations")
                        .HasForeignKey("MeetingLocationId");
                });

            modelBuilder.Entity("ClubScansub.Models.DiveorgCertificate", b =>
                {
                    b.HasOne("ClubScansub.Models.Certificate", "Certificate")
                        .WithMany("Diveorgs")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.Diveorganization", "Diveorg")
                        .WithMany("Certificates")
                        .HasForeignKey("DiveorganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClubScansub.Models.Event", b =>
                {
                    b.HasOne("ClubScansub.Models.Address", "Address")
                        .WithMany("Events")
                        .HasForeignKey("AddressId");

                    b.HasOne("ClubScansub.Models.Divelocation", "Divelocation")
                        .WithMany()
                        .HasForeignKey("DivelocationId");

                    b.HasOne("ClubScansub.Models.Certificate", "RequiredCertificate")
                        .WithMany()
                        .HasForeignKey("RequiredCertificateId");
                });

            modelBuilder.Entity("ClubScansub.Models.EventUser", b =>
                {
                    b.HasOne("ClubScansub.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Events")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClubScansub.Models.UserCertificat", b =>
                {
                    b.HasOne("ClubScansub.Models.Certificate", "Certificate")
                        .WithMany("UserCertificate")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.ApplicationUser", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClubScansub.Models.ApplicationUser", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClubScansub.Models.Course", b =>
                {
                    b.HasOne("ClubScansub.Models.CourseTemplate", "CourseTemplate")
                        .WithMany()
                        .HasForeignKey("CourseTemplateId");
                });
#pragma warning restore 612, 618
        }
    }
}
