//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubScansub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course : Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            //this.SupplementalInstructors = new HashSet<Instructor>();
            //this.CourseSessions = new HashSet<CourseSession>();
        }
    
        public string CourseName { get; set; }
        public CourseTypeEnum CourseType { get; set; }
    
        public virtual Instructor PrimaryInstructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor> SupplementalInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseSession> CourseSessions { get; set; }
        public virtual CourseTemplate CourseTemplate { get; set; }
    }
}
