//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubScansub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSession
    {
        public string DateTime { get; set; }
        public string Duration { get; set; }
        public int Id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Address Address { get; set; }
        public virtual Divelocation Divelocation { get; set; }
        public virtual CourseSessionTemplate CourseSessionTemplate { get; set; }
    }
}
