//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubScansub.Models
{
    using System;
    
    public enum DiveTypeEnum : int
    {
        WreckDive = 0,
        NatureDive = 1,
        TechDive = 2,
        PoolDive = 3
    }
}
