<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>db8cb011-c058-4d4c-b18b-d74e8472cb36</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.9" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="3.1.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClubScansub.DataAccess\ClubScansub.DataAccess.csproj" />
    <ProjectReference Include="..\ClubScansub.Models\ClubScansub.Models.csproj" />
    <ProjectReference Include="..\ClubScansub.Utility\ClubScansub.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Service\" />
  </ItemGroup>


</Project>
